### ISSUE TITLE
Ultra

### ISSUE THREAD

**Issue by snakeboy** [ResetXPDR/DynamicLOD_ResetEdition#3]
I have fps adaption turned off, decrease cloud off, cloud set to Ultra but it keeps kicking it back to high.

**Comment by ResetXPDR** [comment]
That's very strange. Noting that you have FPS adaption turned off, is your FPS when it happens lower than what the target FPS is set for if you did have FPS Adaption enabled?

**Comment by snakeboy** [comment]
No, I have my FPS limit set to very low, it never reaches the limit

**Comment by ResetXPDR** [comment]
I have review the associated code logic and it will not even look at cloud quality, let alone change it, unless FPS Adapation is enabled, FPS Adaption has been activated, and Reduce Cloud Quality is enabled, so I at a loss as to how your installation is experiencing this. 

Actually, I've just had a thought that your cloud quality in the MSFS main menu is set to high and you may be trying to change cloud quality back to Ultra when in a flight. When you exit the flight back to the main menu, the app restores what cloud quality was before the flight and that is what you are experiencing.

If so, the simple solution is to set your MSFS cloud quality either without DynamicLOD running or, if it is, only while you are in the MSFS main menu. Let me know if that fixes it for you.

**Comment by ResetXPDR** [comment]
I am going to close this off as I believe what I stated above will fix it.
