### ISSUE TITLE
MSFS compatibility test failed - Read Only mode

### ISSUE THREAD

**Issue by GXrazy** [ResetXPDR/DynamicLOD_ResetEdition#4]
I always get the message "MSFS compatibility test failed - Read Only mode" in both autofps and dinamicLOD. MSFS simconnect and session are green. I use the latest beta MSFS store version. Thanks.

**Comment by ResetXPDR** [comment]
I am not getting any other reports of the app not working with the current MSFS SU15 beta, so it is likely not that. The other two scenarios in which it is known to occur are:
- There is an issue with permissions and you may need to run the app as Administrator.
- You may have changed MSFS settings in your usercfg.opt file beyond what is possible to set in the MSFS settings menu. To rectify, go into MSFS settings at the main menu and reset to default (F12) the graphics settings for both PC and VR mode, then make all changes to MSFS within the MSFS settings menu.

**Comment by GXrazy** [comment]
Solved. Resetting the graphics options did not work. But I manually reinstalled .Net 7 and ran it as administrator and it works (I don't know which of the 2 things fixed it). Thank you very much for your help.

**Comment by ResetXPDR** [comment]
Excellent. I'm glad I could help.
