### ISSUE TITLE
Add on Top option

### ISSUE THREAD

**Issue by fabianovm** [ResetXPDR/DynamicLOD_ResetEdition#5]
Hello @ResetXPDR , trying to figure out which one is best for me, autofps or dynamiclod (personally I think it is dynamiclod).. can you kindly add on next release the ON TOP checkbox in dynamic_LOD_resetedition, as you did in autofps? Very usefull,  thanks a lot, you can close this, did not know how to contact you in other place, sorry and thanks again!

**Comment by ResetXPDR** [comment]
No problem. I've added it to the wishlist.
